language: groovy
dist: trusty
addons:
  chrome: stable
  firefox: latest

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: true

jdk:
  - openjdk8

#*Set build permissions
#  git update-index --add --chmod=+x travis-build.sh
#  git commit -m "Atualizando travis-build.sh permissões"
#  git push
script: "./travis-build.sh"